fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\AppUser
    from_email:
        address: "test@domain.com"
        sender_name: "test@domain.com"
framework:
    translator: ~
    templating:
        engines: ['twig', 'php']