version: "3.7"
services:
    db:
        image: postgres:12
        restart: always
        environment:
          POSTGRES_PASSWORD: toor
        ports: 
            - "5432:5432"
        volumes:
        - .data:/var/lib/postgresql/data
    web:
        build:
            context: .
            dockerfile: ./docker/dev/nginx/Dockerfile
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - .:/app
            - ./docker/dev/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/dev/nginx/sites-available:/etc/nginx/sites-available
        depends_on: 
            - app
    app:
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile
        volumes:
            - .:/app
        environment: 
            APP_ENV: dev
            DATABASE_URL: sql://root:toor@db/one_local
        ports: 
            - 9000
